### ISSUE TITLE
Index: Link index recursively shows itself inside the iframe

### ISSUE THREAD

**Issue by danmed** [pirate/ArchiveBox#176]
I've just installed and got this working, but have a weird bug.

The first page i archived worked great.. i go to the index page and then click on the text link and it takes me to a nice HTML representation of the page... 

Any subsequent links i archive, the text link takes me to the "Link Index" page, but in the iframe underneath is another copy of the same "Link Index" page...

https://imgur.com/a/UJqJDVc

Eg:

First link i archived, the text link (the title of the page) is linked to : 
https://*****/ArchiveBox/output/archive/1552560659/linuxconfig.org/allow-ssh-root-login-on-ubuntu-18-04-bionic-beaver-linux.html

Any subsequent archived pages, the text links like this : 

https://******/ArchiveBox/output/archive/1552562637/index.html

**Comment by danmed** [comment]
So, a bit more testing.. the problem seems to be that if i send it to a url with an index.html or index.php etc in the actual URL, it works great.. if the URL is just a folder.. then its not and it has this wierd behaviour..

good : 
https://tylermade.net/2017/09/14/the-perfect-reverse-proxy-nginx-ssl-webui-management/index.php

bad:
https://tylermade.net/2017/09/14/the-perfect-reverse-proxy-nginx-ssl-webui-management/

**Comment by pirate** [comment]
Oh yeah I've seen this bug before, I think I know how to fix it.  Before I push anything though, do you mind confirming the git commit hash you're running so I can make sure you're on the latest master.

**Comment by danmed** [comment]
Is this what you're after? f0cf1772

**Comment by pirate** [comment]
Ok I think I fixed it in 61ec497.  Can you try pulling the latest master and giving it a try.

**Comment by danmed** [comment]
Hmm i did a "git pull" but the problem is still there and the interface is
still showing " Archive created using ArchiveBox
<https://github.com/pirate/ArchiveBox> version f0cf1772
<https://github.com/pirate/ArchiveBox/commit/f0cf17722b2f047f1bb5d69c6a16736e09c0ea03>
  "

what have i done wrong here?

**Comment by danmed** [comment]
Ah nevermind.. looks like i needed to add a link for it to refresh the
page...seems to be working now! thanks!
